# Generated by Django 6.0.6 on 2026-06-06 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_lang', models.CharField(max_length=50)),
                ('to_lang', models.CharField(max_length=50)),
                ('input_code', models.TextField()),
                ('output_code', models.TextField(blank=True)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_msg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Conversion histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
